export const HELP_CONTENT = {

  // ── Administrador ──────────────────────────────────────────
  admin: {
    sections: [
      { id: 'primeros-pasos', title: 'Primeros pasos',      page: 'page-admin-home',          permission: 'dashboard.read' },
      { id: 'propietarios',   title: 'Propietarios',        page: 'page-admin-owners',         permission: 'owners.read' },
      { id: 'pagos',          title: 'Pagos',               page: 'page-admin-payments',       permission: 'payments.read' },
      { id: 'deudas',         title: 'Deudas y saldos',     page: null,                        permission: 'debt.read' },
      { id: 'planes',         title: 'Planes de pago',      page: 'page-admin-payment-plans',  permission: 'paymentPlans.read' },
      { id: 'reclamos',       title: 'Reclamos',            page: 'page-admin-claims',         permission: 'claims.read' },
      { id: 'avisos',         title: 'Avisos',              page: 'page-admin-notices',        permission: 'notices.read' },
      { id: 'visitas',        title: 'Visitas',             page: 'page-admin-visits',         permission: 'visits.read' },
      { id: 'libro-visitas',  title: 'Libro de visitas',    page: 'page-admin-visits-log',     permission: 'visits.history.read' },
      { id: 'admins',         title: 'Administradores',     page: 'page-admin-admins',         permission: 'admins.read' },
      { id: 'roles',          title: 'Roles y permisos',    page: 'page-admin-admins',         permission: 'admins.read' },
    ],
    faqs: [
      {
        q: '¿Cómo doy de alta un propietario?',
        a: 'Andá a Propietarios y hacé click en "+ Agregar". Completá nombre, email y contraseña temporal. El propietario recibirá un email con sus datos de acceso.',
        section: 'propietarios',
        page: 'page-admin-owners',
        fn: 'renderOwnersList',
        permission: 'owners.read',
      },
      {
        q: '¿Qué pasa si el propietario ya existe en el sistema?',
        a: 'Si el email ya está registrado, el sistema lo detecta al ingresar el correo. Podés invitarlo a esta organización sin crear un usuario nuevo.',
        section: 'propietarios',
      },
      {
        q: '¿Cómo registro un pago manualmente?',
        a: 'En la pantalla de Pagos, hacé click en "+ Registrar pago". Seleccioná el propietario, el período y el importe. Podés subir un comprobante o dejarlo sin adjunto.',
        section: 'pagos',
        page: 'page-admin-payments',
        fn: 'renderAdminPayments',
        permission: 'payments.read',
      },
      {
        q: '¿Cómo apruebo o rechazo un pago informado?',
        a: 'En Pagos, buscá los que tienen estado "Por aprobar". Hacé click en "Ver" para revisar el comprobante y elegí Aprobar o Rechazar. Si rechazás, podés agregar un motivo.',
        section: 'pagos',
        page: 'page-admin-payments',
        fn: 'renderAdminPayments',
        permission: 'payments.approve',
      },
      {
        q: '¿Cómo cargo un saldo anterior o deuda previa?',
        a: 'Abrí el detalle del propietario desde la pantalla de Propietarios y usá la opción "Agregar deuda". Ingresá el importe y una descripción. Esa deuda quedará visible para el propietario.',
        section: 'deudas',
        page: 'page-admin-owners',
        fn: 'renderOwnersList',
        permission: 'debt.create',
      },
      {
        q: '¿Qué es un ajuste manual?',
        a: 'Es una corrección que el administrador registra sobre la cuenta de un propietario. Puede ser un cargo adicional o una quita, y se refleja en su deuda total.',
        section: 'deudas',
      },
      {
        q: '¿Cómo creo un plan de pago en cuotas?',
        a: 'Desde Planes de pago podés aprobar solicitudes de propietarios o crear un plan directamente. Definís la cantidad de cuotas, la fecha de inicio y si aplica un interés.',
        section: 'planes',
        page: 'page-admin-payment-plans',
        fn: 'renderAdminPaymentPlans',
        permission: 'paymentPlans.read',
      },
      {
        q: '¿Cómo registro el pago de una cuota de un plan?',
        a: 'En la pantalla de Planes de pago, abrí el plan activo del propietario y hacé click en "Registrar pago" sobre la cuota correspondiente.',
        section: 'planes',
        page: 'page-admin-payment-plans',
        fn: 'renderAdminPaymentPlans',
        permission: 'paymentPlans.registerPayment',
      },
      {
        q: '¿Cómo creo un aviso?',
        a: 'Andá a Avisos y hacé click en "+ Nuevo aviso". Elegí el tipo (Informativo, Advertencia o Urgente), escribí el título y el mensaje. Podés enviar una notificación push al mismo tiempo.',
        section: 'avisos',
        page: 'page-admin-notices',
        fn: 'renderAdminNotices',
        permission: 'notices.create',
      },
      {
        q: '¿Cómo respondo un reclamo?',
        a: 'En Reclamos, hacé click en "Ver" sobre el reclamo. Podés cambiar el estado (En proceso / Resuelto) y agregar una nota de respuesta que el propietario verá en su app.',
        section: 'reclamos',
        page: 'page-admin-claims',
        fn: 'renderAdminClaims',
        permission: 'claims.respond',
      },
      {
        q: '¿Cómo invito a otro administrador?',
        a: 'En Administradores, buscá al propietario por nombre o email y hacé click en "Invitar". El propietario debe estar registrado en la organización. Elegí el rol que va a tener.',
        section: 'admins',
        page: 'page-admin-admins',
        fn: 'renderAdminAdministrators',
        permission: 'admins.create',
      },
      {
        q: '¿Cómo asigno roles y permisos a un administrador?',
        a: 'En Administradores, hacé click en "Rol" junto al administrador y elegí el nuevo rol. Cada rol tiene un conjunto de acciones habilitadas que podés ver antes de confirmar.',
        section: 'roles',
        page: 'page-admin-admins',
        fn: 'renderAdminAdministrators',
        permission: 'admins.update',
      },
      {
        q: '¿Qué puede hacer el rol Vigilador?',
        a: 'El rol Vigilador solo tiene acceso al módulo de Visitas: puede ver las visitas del día, registrar ingresos y egresos, y consultar el libro de visitas. No accede a pagos ni datos administrativos.',
        section: 'roles',
      },
      {
        q: '¿Cómo consulto el libro de visitas?',
        a: 'En el menú de Visitas encontrás la opción "Libro de visitas". Podés filtrar por fecha para ver todos los ingresos y egresos registrados por portería.',
        section: 'libro-visitas',
        page: 'page-admin-visits-log',
        fn: 'renderAdminVisitsLog',
        permission: 'visits.history.read',
      },
    ],
  },

  // ── Propietario ────────────────────────────────────────────
  owner: {
    sections: [
      { id: 'primer-ingreso', title: 'Primer ingreso',       page: null },
      { id: 'pagos',          title: 'Pagos y recibos',      page: 'page-owner-pay' },
      { id: 'planes',         title: 'Plan de pagos',        page: 'page-owner-payment-plans' },
      { id: 'reclamos',       title: 'Reclamos',             page: 'page-owner-claims' },
      { id: 'avisos',         title: 'Avisos',               page: 'page-owner-notices' },
      { id: 'perfil',         title: 'Mi perfil',            page: 'page-owner-profile' },
    ],
    faqs: [
      {
        q: '¿Cómo ingreso por primera vez?',
        a: 'Abrí el link que recibiste por email, ingresá tu dirección de correo y la contraseña temporal. La app te va a pedir que la cambies antes de continuar.',
        section: 'primer-ingreso',
      },
      {
        q: '¿Por qué debo cambiar mi contraseña temporal?',
        a: 'La contraseña temporal la genera el administrador. Por seguridad, tenés que reemplazarla por una propia que solo vos conozcas.',
        section: 'primer-ingreso',
      },
      {
        q: '¿Cómo veo mi deuda pendiente?',
        a: 'En la pantalla de inicio ves el estado actual de tu cuenta. Si tenés deuda, también podés acceder a Pagar para ver el detalle de los períodos adeudados.',
        section: 'pagos',
        page: 'page-owner-pay',
        fn: 'renderUploadPage',
      },
      {
        q: '¿Cómo informo un pago?',
        a: 'Andá a Pagar, seleccioná los períodos que querés abonar y adjuntá el comprobante (foto o PDF). El administrador lo revisa y te confirma la aprobación.',
        section: 'pagos',
        page: 'page-owner-pay',
        fn: 'renderUploadPage',
      },
      {
        q: '¿Cuándo puedo descargar un recibo?',
        a: 'El recibo está disponible una vez que el administrador aprueba tu pago. Lo encontrás en el historial de pagos, en la sección Inicio → Ver mis pagos.',
        section: 'pagos',
        page: 'page-owner-history',
        fn: 'renderOwnerHistory',
      },
      {
        q: '¿Cómo solicito un plan de pagos?',
        a: 'Desde Pagar, seleccioná los conceptos que querés financiar y hacé click en "Solicitar plan de pagos". Podés agregar un comentario para el administrador.',
        section: 'planes',
        page: 'page-owner-payment-plans',
        fn: 'renderOwnerPaymentPlans',
      },
      {
        q: '¿Qué significa que una deuda esté regularizada en plan de pagos?',
        a: 'Significa que el administrador aprobó tu solicitud y la deuda está siendo pagada en cuotas. Cada cuota tiene su fecha de vencimiento y podés ver el estado desde la sección de planes.',
        section: 'planes',
        page: 'page-owner-payment-plans',
        fn: 'renderOwnerPaymentPlans',
      },
      {
        q: '¿Cómo hago un reclamo?',
        a: 'En Reclamos, hacé click en "+ Nuevo reclamo". Elegí la categoría (infraestructura, ruidos, limpieza, etc.), describí el problema y envialo. El administrador te notifica cuando lo atiende.',
        section: 'reclamos',
        page: 'page-owner-claims',
        fn: 'renderOwnerClaims',
      },
      {
        q: '¿Cómo veo los avisos?',
        a: 'Los avisos están en la sección Comunidad → Avisos. Los urgentes aparecen destacados. También podés recibir notificaciones en tu celular si habilitás los permisos correspondientes.',
        section: 'avisos',
        page: 'page-owner-notices',
        fn: 'renderOwnerNotices',
      },
      {
        q: '¿Cómo cambio mi email?',
        a: 'Andá a Mi perfil → Cambiar email. Ingresá el nuevo correo y confirmá el cambio. Tu próximo ingreso será con el email nuevo.',
        section: 'perfil',
        page: 'page-owner-profile',
        fn: 'renderOwnerProfile',
      },
      {
        q: '¿Qué hago si olvidé mi contraseña?',
        a: 'En la pantalla de inicio de sesión, hacé click en "¿Olvidaste tu contraseña?". Ingresá tu email y te vamos a mandar un enlace para restablecerla (válido por 10 minutos).',
        section: 'primer-ingreso',
      },
    ],
  },

  // ── Vigilador / Portería ───────────────────────────────────
  guard: {
    sections: [
      { id: 'visitas-del-dia', title: 'Visitas del día',   page: 'page-admin-visits' },
      { id: 'ingreso',         title: 'Registrar ingreso', page: 'page-admin-visits' },
      { id: 'egreso',          title: 'Registrar egreso',  page: 'page-admin-visits' },
      { id: 'libro-visitas',   title: 'Libro de visitas',  page: 'page-admin-visits-log' },
    ],
    faqs: [
      {
        q: '¿Cómo veo las visitas autorizadas?',
        a: 'Al ingresar a la app, la pantalla principal muestra todas las visitas registradas para el día de hoy con su estado actual.',
        section: 'visitas-del-dia',
        page: 'page-admin-visits',
        fn: 'renderAdminVisits',
      },
      {
        q: '¿Cómo busco una visita?',
        a: 'Usá la barra de búsqueda en la parte superior para buscar por nombre del visitante, nombre del propietario o número de unidad.',
        section: 'visitas-del-dia',
      },
      {
        q: '¿Cómo registro el ingreso de una visita?',
        a: 'Buscá la visita en la lista y verificá que tenga estado "Aprobada". Hacé click en "Registrar ingreso", agregá una observación si es necesario y confirmá.',
        section: 'ingreso',
        page: 'page-admin-visits',
        fn: 'renderAdminVisits',
      },
      {
        q: '¿Cómo registro el egreso de una visita?',
        a: 'Buscá la visita que tiene estado "Adentro". Hacé click en "Registrar egreso", agregá una observación si es necesario y confirmá.',
        section: 'egreso',
        page: 'page-admin-visits',
        fn: 'renderAdminVisits',
      },
      {
        q: '¿Qué es la observación al registrar un ingreso o egreso?',
        a: 'Es una nota libre que quedará guardada en el historial. Podés usarla para dejar constancia de: vehículo y patente, documento presentado, personas acompañantes u otras situaciones relevantes.',
        section: 'ingreso',
      },
      {
        q: '¿Cómo consulto el libro de visitas?',
        a: 'En el menú inferior, hacé click en "Libro de visitas". Podés filtrar por fecha para ver todos los ingresos y egresos del día o de días anteriores.',
        section: 'libro-visitas',
        page: 'page-admin-visits-log',
        fn: 'renderAdminVisitsLog',
      },
      {
        q: '¿Qué hago si una visita no aparece?',
        a: 'Si el visitante llega y no hay ninguna visita registrada, no lo ingresés. Contactá al propietario para que registre la visita desde su celular. Una vez aprobada, vas a ver el botón de ingreso.',
        section: 'visitas-del-dia',
      },
    ],
  },
};
